# app/routers/loan_link.py

from typing import List, Optional

from fastapi import APIRouter, Depends, HTTPException, status
from sqlalchemy.orm import Session

from .. import schema
from ..db import get_db
from ..crud import loan_link_crud, organization_crud, loan_product_crud
from ..security import require_roles

router = APIRouter(
    prefix="/loan-links",
    tags=["Loan Links"],
)



@router.post(
    "/",
    response_model=schema.CompanyLoanLinkOut,
    status_code=status.HTTP_201_CREATED,
)
def create_company_loan_link(
    organization_id: int,
    product_id: int,
    link_in: Optional[schema.CompanyLoanLinkCreate] = None,
    db: Session = Depends(get_db),
    current_admin=Depends(
        require_roles([
            schema.UserRoleEnum.ADMIN,
            schema.UserRoleEnum.MANAGER,
        ])
    ),
):
    """
    Create a new company loan link for a specific organization + product.
    The token is generated by the backend.
    """
    org = organization_crud.get_organization(db, organization_id)
    if not org:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Organization not found.",
        )

    product = loan_product_crud.get_loan_product(db, product_id)
    if not product or not product.is_active:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Loan product is not active or does not exist.",
        )

    expires_at = link_in.expires_at if link_in else None

    create_payload = schema.CompanyLoanLinkCreate(
        organization_id=organization_id,
        product_id=product_id,
        expires_at=expires_at,
    )

    return loan_link_crud.create_company_loan_link(db, create_payload)


@router.get(
    "/",
    response_model=List[schema.CompanyLoanLinkOut],
)
def list_company_loan_links(
    organization_id: Optional[int] = None,
    product_id: Optional[int] = None,
    skip: int = 0,
    limit: int = 100,
    db: Session = Depends(get_db),
    current_admin=Depends(
        require_roles([
            schema.UserRoleEnum.ADMIN,
            schema.UserRoleEnum.LOAN_OFFICER,
            schema.UserRoleEnum.MANAGER,
        ])
    ),
):
    """
    List company loan links, optionally filtered by organization or product.
    """
    return loan_link_crud.list_links(
        db,
        organization_id=organization_id,
        product_id=product_id,
        skip=skip,
        limit=limit,
    )


@router.get(
    "/{link_id}",
    response_model=schema.CompanyLoanLinkOut,
)
def get_company_loan_link(
    link_id: int,
    db: Session = Depends(get_db),
    current_admin=Depends(
        require_roles([
            schema.UserRoleEnum.ADMIN,
            schema.UserRoleEnum.LOAN_OFFICER,
            schema.UserRoleEnum.MANAGER,
        ])
    ),
):
    link = loan_link_crud.get_link(db, link_id)
    if not link:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Loan link not found.",
        )
    return link


@router.patch(
    "/{link_id}/deactivate",
    response_model=schema.CompanyLoanLinkOut,
)
def deactivate_company_loan_link(
    link_id: int,
    db: Session = Depends(get_db),
    current_admin=Depends(require_roles([schema.UserRoleEnum.ADMIN])),
):
    link = loan_link_crud.get_link(db, link_id)
    if not link:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Loan link not found.",
        )
    return loan_link_crud.deactivate_link(db, link)


@router.get(
    "/public/{token}",
    response_model=schema.CompanyLoanLinkOut,
)
def get_public_company_loan_link_by_token(
    token: str,
    db: Session = Depends(get_db),
):
    link = loan_link_crud.get_link_by_token(db, token)
    if not link:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Invalid or expired loan link.",
        )
    if not link.is_active:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="This loan link is no longer active.",
        )


    return {
        "id": link.id,
        "token": link.token,
        "organization_id": link.organization_id,
        "product_id": link.product_id,
        "is_active": link.is_active,
        "expires_at": link.expires_at,
        "created_at": link.created_at,
        "organization_name": link.organization.name if link.organization else None,
        "loan_product_name": link.product.name if link.product else None,
    }
